---
apiVersion: nnf.cray.hpe.com/v1alpha2
kind: NnfContainerProfile
metadata:
  name: demo
  namespace: nnf-system
data:
  storages:
    - name: DW_JOB_my_storage
      optional: false
  # $NNF_CONTAINER_PORTS can be used to get the port number(s)
  numPorts: 1
  mpiSpec:
    mpiReplicaSpecs:
      Launcher:
        template:
          spec:
            containers:
              - name: nnf-container-example
                image: ghcr.io/nearnodeflash/nnf-container-example:latest
                command:
                  - mpirun
                  - mpi_hello_world
                  - "$(DW_JOB_my_storage)"
                  # An example webserver can be started using python
                  # - mpirun
                  # - python3
                  # - -m
                  # - http.server
                  # - $(NNF_CONTAINER_PORTS)
      Worker:
        template:
          spec:
            containers:
              - name: nnf-container-example
                image: ghcr.io/nearnodeflash/nnf-container-example:latest
                env:
                  - name: NNF_NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  - name: DEAN1
                    value: thing1
  retryLimit: 2
---
apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: demo-container
  namespace: default
spec:
  desiredState: "Proposal"
  dwDirectives:
    - "#DW jobdw name=demo-gfs2 type=gfs2 capacity=50GB"
    - "#DW container name=demo-container profile=demo \
      DW_JOB_my_storage=demo-gfs2"
  wlmID: "Bubbly WLM"
  jobID: "bubbles 900001"
  userID: 1050
  groupID: 1052
