---
apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: nnf-container-example-profile
  namespace: nnf-system
data:
  storages:
    - name: DW_JOB_my_storage
      optional: false
    - name: DW_PERSISTENT_my_lustre
      optional: true
  mpiSpec:
    mpiReplicaSpecs:
      Launcher:
        template:
          spec:
            containers:
              - name: nnf-container-example
                image: ghcr.io/nearnodeflash/nnf-container-example:latest
                command:
                  - mpirun
                  - mpi_hello_world
                  - "$(DW_JOB_my_storage)"
                  - "$(DW_PERSISTENT_my_lustre)"
      Worker:
        template:
          spec:
            containers:
              - name: nnf-container-example
                image: ghcr.io/nearnodeflash/nnf-container-example:latest

---
apiVersion: dws.cray.hpe.com/v1alpha1
kind: Workflow
metadata:
  name: nnf-container-example
  namespace: default
spec:
  desiredState: "Proposal"
  dwDirectives:
    - "#DW persistentdw name=blake-persistent"
    - "#DW jobdw name=nnf-container-example-gfs2 type=gfs2 capacity=50GB"
    - "#DW container name=nnf-container-example profile=nnf-container-example-profile \
      DW_JOB_my_storage=nnf-container-example-gfs2 \
      DW_PERSISTENT_my_lustre=blake-persistent"
  wlmID: "5f239bd8-30db-450b-8c2c-a1a7c8631a1a"
  jobID: 900001
  userID: 1050
  groupID: 1051
